Replace use of JAXB with commons-codec
This fixes a NoClassDefFoundError when building with a Java 11 SDK, caused by lines like this: `import javax.xml.bind.DatatypeConverter;`

JAXB isn’t available by default from Java 9 onwards. Could have added them as a dependency but felt like it was a weird dependency to introduce. commons-codec seemed more suitable.

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception